did markup on the layout of lesson_2
Anastasia-Kraeva/HTML5_and_CSS3 pull request #2
Opened 2020-08-27 07:25 UTC by Anastasia-Kraeva

2020-08-27 11:26 UTC, lipa88-mk requested changes

2020-08-27 11:26 UTC, lipa88-mk commented on lesson_2/css/style.scss
> +    max-width: ($width_container - $padding_container*2)/2 - 20px - 60px; // пока делала вторую часть страницы где-то накосячила и после этого в формулу пришлось добавить вычетание 60px потому что бл
Если использовать новую модель подсчета с box-sizing border-box, , то не нужно было бы учитывать паддинги в подсчете

2020-08-27 11:26 UTC, lipa88-mk commented on lesson_2/css/style.scss
> +    .product__img { // не понимаю почему в версии для телефонов ширина родительского блока (с фоном) не ключает в себя ширину изображения
потому что ширина браузера на мобильных от 320 до примерно 600 пикселей, а картинка ровно 500,  и не тянется. Поэтому на маленьких экранах она вылезает за область просмотра. Пока это нормально, позже дополним в адаптиве.

2020-08-27 11:26 UTC, lipa88-mk commented on lesson_2/css/style.scss
> +        max-width: $width_container/2;
Можно примерно, лишь бы текст не наползал на картинку справа, а переносился вниз.

2020-08-27 11:26 UTC, lipa88-mk commented on lesson_2/css/style.scss
> +        border-radius: 50%;
потому что паддинг влияет на итоговый размер элемента, добаляя его с одной стороны получается прямоугольник,  а при использовании скругления - друга фигура.  К картинке паддинги не очень хорошо применять, тк у нее нет внутреннего содержимого и опять же помогает box-sizing

2020-08-27 11:26 UTC, lipa88-mk commented on lesson_2/css/style.scss
> +        min-width: 500px; // не знаю как лучше задать ширину полям ввода
млжно в процентах, можно в пикселях, как и любому другому элементу.

2020-08-27 11:26 UTC, lipa88-mk commented on lesson_2/css/style.scss
> +        align-items: center; // не понимаю почему кнопка продолжает растягиваться по ширине
Потому что у родителя flex-direction: column, направление осей стало другим

2020-08-27 11:26 UTC, lipa88-mk commented on lesson_2/css/style.scss
> +    * {
так лучше не делать, вы все элементы сделали блоками, а это не очень хорошо. Напишите лучше отдельные правила, для кого display flex должен замениться на block

2020-08-29 08:29 UTC, Anastasia-Kraeva commented on lesson_2/css/style.scss
> +    .product__img { // не понимаю почему в версии для телефонов ширина родительского блока (с фоном) не ключает в себя ширину изображения
меня удивило не то, что она не тянется, а то, что ее будто выдернуло из дива с фоном, почему фон занимает только половину экрана  https://pastenow.ru/6e38222e7fafadb2780a36e923434497

2020-08-29 08:40 UTC, Anastasia-Kraeva commented on lesson_2/css/style.scss
> +        border-radius: 50%;
да интересно получилось), кстати box-sizing не срабатывает, но с пониманием ошибки стала проще относиться к этому, спасибо

2020-08-29 08:49 UTC, Anastasia-Kraeva commented on lesson_2/css/style.scss
> +    * {
но ведь ниже я сделала ссылки строчными, я могу туда и другие теги добавить

2020-08-29 13:09 UTC, lipa88-mk commented on lesson_2/css/style.scss
> +    .product__img { // не понимаю почему в версии для телефонов ширина родительского блока (с фоном) не ключает в себя ширину изображения
Попробуйте уменьшить ширину картинки на этой ширине экрана и посмотреть как будет вести себя фон. Возможно фону стоит задать ширину дополнительно

2020-08-29 13:10 UTC, lipa88-mk commented on lesson_2/css/style.scss
> +    * {
Так лучше не делать. Это как снести дом, когда хотелось перекрасить окна)

2020-09-05 13:01 UTC, merged